@startuml

scale 350 width
[*] --> NoWord
NoWord --> Word: Letter
NoWord --> NoWord: Other
Word --> NoWord: NoLetter; counter++
Word --> Word: Letter
NoWord --> Tag: <
Tag --> NoWord: >
Tag --> Tag: Other
Tag --> AltText: "
AltText --> Tag: "
AltText --> AltText: No "
@enduml